version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:992"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
  gateway:
    image: docker_account/gateway:latest
    container_name: gateway
    ports:
      - "8081:8081"
    depends_on:
      - "kafka"
  bpe:
    image: docker_account/bpe:latest
    container_name: bpe
    ports:
      - "8082:8082"
    depends_on:
      - "kafka"
  worker-userinfo:
    image: docker_account/worker-userinfo:latest
    container_name: worker-userinfo
    depends_on:
      - "kafka"
  worker-payment:
    image: docker_account/worker-payment:latest
    container_name: worker-payment
    depends_on:
      - "kafka"